### ISSUE TITLE
require() of ES modules is not supported // ERR_REQUIRE_ESM

### ISSUE THREAD

**Issue by majdi** [datocms/plugins-sdk#14]
Hello,

I'm a DatoCMS lover and I just start using the plugins-sdk to create my own :)
I have a little issue with the package which is ES module format ready. 

```sh
error - Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /[...]/node_modules/lodash-es/get.js
require() of ES modules is not supported.
require() of /[...]/node_modules/lodash-es/get.js from /[...]/node_modules/datocms-plugins-sdk/lib/index.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename get.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /[...]/node_modules/lodash-es/package.json.
```

There is of course still the solution to use the entry point :
```html
<script src="https://unpkg.com/datocms-plugins-sdk"></script>
```

I don't know if it's the best option when we can import it and as ES modules are still experimental is there any reason to keep it for this plugin ? :)

Thanks ✌️

**Comment by stefanoverna** [comment]
Hey @majdi in the meantime we published a completely renewed plugin system, much more powerful. Can you please try that and let us know how it goes? 

Announcement: https://www.datocms.com/blog/introducing-plugins-v2-better-in-every-possibile-way
Docs: https://www.datocms.com/docs/plugin-sdk

Thanks!

**Comment by majdi** [comment]
Hey, thanks I'll try it next week ;)
