### ISSUE TITLE
React UI: The muted button does not have a visually distinct disabled state

### ISSUE THREAD

**Issue by idrm** [datocms/plugins-sdk#16]
Perhaps it's by design, but the muted button type (and unlike the primary and negative button types) does not have an explicit styling for its disabled state so it remains the same visually when that state is turned on.

This applies to version 0.3.17 of the `datocms-react-ui` package.

The relevant styling file is located here: https://github.com/datocms/plugins-sdk/blob/master/packages/react-ui/src/Button/styles.module.css. Note that lack of a `&.disabled` selector inside the `.buttonType-muted` class.

**Comment by stefanoverna** [comment]
You're right! v0.3.18 fixes the issue!
