### ISSUE TITLE
DatoCMS instance crashes when you don't use a correct Font-Awesome icon name

### ISSUE THREAD

**Issue by velomovies** [datocms/plugins-sdk#24]
Hi @stefanoverna,

We are currently working on a custom page plugin and we want to be able to make the user choose a icon from Font Awesome for the mainNavigationTabs link. With this I came accross an error that makes it really difficult to develop or release the plugin. 

When we add an item to the navigation tab like so:
```tsx
import { connect, IntentCtx, RenderPageCtx } from 'datocms-plugin-sdk'

import PageScreen from './entrypoints/PageScreen/PageScreen'
import { render } from './utils/render'

import 'datocms-react-ui/styles.css'
import './styles/index.css'

connect({
  mainNavigationTabs(ctx: IntentCtx) {
    return [
      {
        label: 'Page',
        icon: 'cogs',
        placement: ['before', 'content'],
        pointsTo: {
          pageId: 'page',
        },
      },
    ]
  },
  renderPage(pageId, ctx: RenderPageCtx) {
    if (pageId === 'page') {
      return render(<PageScreen ctx={ctx} />)
    }
  },
})
```
I get a page and a link like I expect. But when I now try to add another random icon (like `walkie-talkie` https://fontawesome.com/icons/walkie-talkie?f=classic&s=solid) like this:
```tsx
import { connect, IntentCtx, RenderPageCtx } from 'datocms-plugin-sdk'

import PageScreen from './entrypoints/PageScreen/PageScreen'
import { render } from './utils/render'

import 'datocms-react-ui/styles.css'
import './styles/index.css'

connect({
  mainNavigationTabs(ctx: IntentCtx) {
    return [
      {
        label: 'Page',
        icon: 'walkie-talkie',
        placement: ['before', 'content'],
        pointsTo: {
          pageId: 'page',
        },
      },
    ]
  },
  renderPage(pageId, ctx: RenderPageCtx) {
    if (pageId === 'page') {
      return render(<PageScreen ctx={ctx} />)
    }
  },
})
```
 I get an error and I am not able to use the Dato instance anymore. 

Some font-awesome icons indeed work, but I found it really hard to know which ones I could actually use (and thus make sure the user doesn't choose an Font-Awesome icon that creates an error in Dato). The only insight I have is that I got the impression that the only icons that work, where the Pro icons from Font Awesome version 5.8.2. All icons released in later versions don't seem to work. 

Since this will crash your DatoCMS instance instantly this looks like an issue that needs a fix from your side (like not showing an icon at all if the icon doesn't exist or set a default icon?), but maybe there is another fix to mitigate this problem? I hope to hear from you soon!

**Comment by stefanoverna** [comment]
Hi @velomovies and thanks for your detailed report!

We've implemented the following changes:

* We've upgraded to the latest version of FontAwesome 5 — a lot of new icons are available now!
* In v0.7.7 of datocms-plugin-sdk we [explicitly define in Typescript](https://github.com/datocms/plugins-sdk/blob/master/packages/sdk/src/types.ts#L1671) which icons are supported — [only solid ones are](https://fontawesome.com/v5/search?o=r&s=solid). This helps developers  by enabling auto-completion of icon names in VS Code, and prevents errors;
* If you're still sending us a non-existent icon, DatoCMS instance replaces it with a cross icon, and notifies the developer in the console with an error;

![Screenshot 2023-04-14 at 16 29 18](https://user-images.githubusercontent.com/51573/232073273-223ae1ad-24ce-4597-b297-6bd553c888e9.png)
