### ISSUE TITLE
Sidebar dissapears with `contentAreaSidebarItems`

### ISSUE THREAD

**Issue by velomovies** [datocms/plugins-sdk#25]
Hi again @stefanoverna,

Thanks for the fast reply on my previous issue. I'm raising this issue more as a question and I'm interested to see if this is something that could be changed or if this works as designed. 

When I add the `settingsAreaSidebarItemGroups` and click on the link it opens the page as expected, rendering it inside the settings page. 
Like so: 
```typescript
import { connect, IntentCtx, RenderPageCtx } from 'datocms-plugin-sdk'

import PageScreen from './entrypoints/PageScreen/PageScreen'
import { render } from './utils/render'

import 'datocms-react-ui/styles.css'
import './styles/index.css'

connect({
  settingsAreaSidebarItemGroups(ctx: IntentCtx) {
    return [
      {
        label: 'Custom page',
        placement: ['before', 'permissions'],
        items: [
          {
            label: 'Page',
            icon: 'cogs',
            placement: ['before', 'content'],
            pointsTo: {
              pageId: 'page',
            },
          },
        ],
     }
  },
  renderPage(pageId, ctx: RenderPageCtx) {
    if (pageId === 'page') {
      return render(<PageScreen ctx={ctx} />)
    }
  },
})
```
![settings](https://user-images.githubusercontent.com/22169955/232430939-e6924459-ec0e-4913-be71-fb11e59fdcc6.png)

But when I do the same with `contentAreaSidebarItems`, click the link and open the page it will open in a fully new view and the sidebar disappears. 
Like so:
```typescript
import { connect, IntentCtx, RenderPageCtx } from 'datocms-plugin-sdk'

import PageScreen from './entrypoints/PageScreen/PageScreen'
import { render } from './utils/render'

import 'datocms-react-ui/styles.css'
import './styles/index.css'

connect({
  contentAreaSidebarItems(ctx: IntentCtx) {
    return [
      {
        label: 'Page',
        icon: 'cogs',
        placement: ['before', 'menuItems'],
        pointsTo: {
          pageId: 'page',
        },
      },
    ]
  },
  renderPage(pageId, ctx: RenderPageCtx) {
    if (pageId === 'page') {
      return render(<PageScreen ctx={ctx} />)
    }
  },
})
```

![sidebar](https://user-images.githubusercontent.com/22169955/232431008-6af407c7-2276-4c03-bac6-a6f120ea534e.png)

I expect the sidebar to still be visible (or have an option to show/hide the sidebar). Is this something that is possible or could be added?

Thanks in advance!

**Comment by stefanoverna** [comment]
That was a regression, thanks for spotting it! We should have fixed it now!
