### ISSUE TITLE
Dropdown does not expand it's menu

### ISSUE THREAD

**Issue by palmamartin** [datocms/plugins-sdk#28]
We are facing the problem when using the [Dropdown](https://www.datocms.com/docs/plugin-sdk/dropdown) UI element that it  does not expand fully see:

<img width="770" alt="Screenshot 2023-10-25 at 09 07 35" src="https://github.com/datocms/plugins-sdk/assets/381/74c61e86-5405-4ece-bca4-b7cdfac9e41c">

Also inside inside a fieldset:

<img width="837" alt="Screenshot 2023-10-25 at 09 08 00" src="https://github.com/datocms/plugins-sdk/assets/381/eadddb50-cf99-4489-b04f-423ee3c2efe5">

Any suggestion what we do wrong?

Here is the code:

```jsx
<Canvas ctx={props.ctx}>
      {isEnabled ? (
        <Dropdown
          renderTrigger={({ open, onClick }) => (
            <Button
              onClick={onClick}
              leftIcon={<CreateIcon />}
              rightIcon={open ? <CaretUpIcon /> : <CaretDownIcon />}
              
            >
              Create new...
            </Button>
          )}
        >
          <DropdownMenu>
            <DropdownOption onClick={() => {}}>
              Individual list for all locales
            </DropdownOption>
            <DropdownOption onClick={() => {}}>
              Single list for all locales
            </DropdownOption>
            <DropdownOption onClick={() => {}}>
              Single list only for {props.ctx.locale.toUpperCase()}
            </DropdownOption>
            <DropdownSeparator />
          </DropdownMenu>
        </Dropdown>
      ) : null}
    </Canvas>
```

**Comment by stefanoverna** [comment]
It is just that you're using a Dropdown in a field addon. Field addons iframe height is calculated automatically based on its content (in your case, a button). So the drop down does not have any space to expand.

**Comment by stefanoverna** [comment]
I would suggest you pass the prop noAutoresizer={true} to the <Canvas /> component, and manually set an height for the iframe with `ctx.updateHeight(<NEW_HEIGHT>)`.

https://github.com/datocms/plugins-sdk/blob/master/packages/sdk/src/connect.ts#L61-L76

**Comment by palmamartin** [comment]
Thanks for the help, this solves my problem!
